In [1]:
#PART A
#1. load the dataset and display first five records

import pandas as pd

df = pd.read_csv('Dataset 2.csv')
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [2]:
#2. detemine number of rows and columns

df.shape

(750, 10)

In [3]:
#3. display all column names

df.columns

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

In [4]:
#4. identify numerical and categorical features

print("Numerical Features:")
print(df.select_dtypes(include=['int64','float64']).columns)

print("\nCategorical Features:")
print(df.select_dtypes(include=['object']).columns)

Numerical Features:
Index(['UserID', 'Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks',
       'MonthlySpend'],
      dtype='object')

Categorical Features:
Index(['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed'], dtype='object')

In [5]:
#5. check missing values

df.isnull().sum()

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

In [6]:
#PART B
#6. calculate average age of users

df['Age'].mean()

np.float64(41.824)

In [7]:
#7. determine average watch hours per week

df['WatchHoursPerWeek'].mean()

np.float64(14.236)

In [8]:
#8. find average monthly spending

df['MonthlySpend'].mean()

np.float64(689.9053333333334)

In [9]:
#9. count users in each subscription category

df['SubscriptionType'].value_counts()

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

In [10]:
#10. percentage of users who renewed subscriptions

(df['SubscriptionRenewed'].value_counts(normalize=True) * 100)

SubscriptionRenewed
No     53.733333
Yes    46.266667
Name: proportion, dtype: float64

In [11]:
#PART C
#11. convert categorical features into numerical form

from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

encoder = LabelEncoder()

df_encoded['Gender'] = encoder.fit_transform(df_encoded['Gender'])
df_encoded['SubscriptionType'] = encoder.fit_transform(df_encoded['SubscriptionType'])
df_encoded['FavoriteGenre'] = encoder.fit_transform(df_encoded['FavoriteGenre'])
df_encoded['SubscriptionRenewed'] = encoder.fit_transform(df_encoded['SubscriptionRenewed'])

df_encoded.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,0,0,23,5,1,13,353,0
1,1002,55,1,0,9,4,2,14,317,1
2,1003,49,1,0,8,3,1,16,309,0
3,1004,39,0,1,19,5,2,45,833,1
4,1005,38,0,1,23,5,5,24,804,1

In [12]:
#12. define feature set (x)and target variable (y)

X = df_encoded.drop('SubscriptionRenewed', axis=1)
y = df_encoded['SubscriptionRenewed']

print(X.head())
print(y.head())

   UserID  Age  Gender  SubscriptionType  WatchHoursPerWeek  DevicesUsed  \
0    1001   22       0                 0                 23            5
1    1002   55       1                 0                  9            4
2    1003   49       1                 0                  8            3
3    1004   39       0                 1                 19            5
4    1005   38       0                 1                 23            5

   FavoriteGenre  AdClicks  MonthlySpend
0              1        13           353
1              2        14           317
2              1        16           309
3              2        45           833
4              5        24           804
0    0
1    1
2    0
3    1
4    1
Name: SubscriptionRenewed, dtype: int64

In [13]:
#13. split dataset into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(600, 9)
(150, 9)

In [14]:
#PART D
#14. train decision tree model

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [15]:
#15. evaluate model using accuracy

from sklearn.metrics import accuracy_score

y_pred_dt = dt.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", accuracy_dt)

Decision Tree Accuracy: 0.5666666666666667

In [16]:
#16. generate confusion matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_dt)

print(cm)

[[50 32]
 [33 35]]

In [17]:
print("TN =", cm[0][0])
print("FP =", cm[0][1])
print("FN =", cm[1][0])
print("TP =", cm[1][1])

TN = 50
FP = 32
FN = 33
TP = 35

In [18]:
#PART E
#17. train KNN classifier (K=5)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [19]:
#18. compare KNN accuracy with decision tree

y_pred_knn = knn.predict(X_test)

accuracy_knn = accuracy_score(y_test, y_pred_knn)

print("Decision Tree Accuracy =", accuracy_dt)
print("KNN Accuracy =", accuracy_knn)

Decision Tree Accuracy = 0.5666666666666667
KNN Accuracy = 0.6

In [20]:
#PART F
#19. train linear regression model for monthlyspend

from sklearn.linear_model import LinearRegression

X_reg = df_encoded.drop('MonthlySpend', axis=1)
y_reg = df_encoded['MonthlySpend']

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

lr = LinearRegression()

lr.fit(X_train_reg, y_train_reg)

LinearRegression()

In [21]:
#20. predict monthly spening for a new user

new_user = [[
    2000,  # UserID
    30,    # Age
    1,     # Gender
    1,     # SubscriptionType
    20,    # WatchHoursPerWeek
    3,     # DevicesUsed
    0,     # FavoriteGenre
    15,    # AdClicks
    1      # SubscriptionRenewed
]]

prediction = lr.predict(new_user)

print("Predicted Monthly Spend = ₹", prediction[0])

Predicted Monthly Spend = ₹ 849.0946300195128

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(